### ISSUE TITLE
Standalone version is much slower than in the editor

### ISSUE THREAD

**Issue by Wenzy--** [NullTale/GiLight2D#1]
Hi,
This repository is amazing.But I have encountered an issue.I created a scene with cubes and try to render in 2d Lighting. But I found when I export the scene as an standalone program.It would be slower than run in the editor. I have located the issue by Unity Profile .

 The vSync consumption is high in standalone version and it can't be disabled. (In the editor,vSync is not actived)

I have try to set a property in editor. "  ProjectSettings- Quality - Vsync Count "  to Don't Sync. And also try to set it by code.
Application.targetFrameRate = 300
QualitySettings.vSyncCount = 0

But still can't disable Vsync. Have tested in Unity2021 LTS and 2022 LTS

**Comment by NullTale** [comment]
So I checked the performance, in general everything works as it should, I can only advise you to check the settings of the video card driver. Also want to say that performance it strongly depends on the resolution, because the lighting is calculated for each pixel . And there's another case if used noise texture that depends on the screen resolution and dynamic resolution is enabled it will be recreated every time the resolution changes, this may affect performance. In general, it's working as it should. 

https://github.com/NullTale/GiLight2D/assets/1497430/907b8433-0e4d-4467-945f-85cedde21d8d

**Comment by Wenzy--** [comment]
Thanks for the feed back! But I think the graphic usage is not intense so it may not reflect the difference between running in an editor and running as a standalone application.

I have tried upgrading my graphics card driver ,change the settings make sure it don't enable Vsync automatically and also have try running it on another computer. But the standalone version is still slower than in the editor. I'm not sure if it is caused by Vsync.

On the demo scene,I have create a luminous cube. In the editor, it runs at 43fps, but in the standalone app, it is 36fps.

My "Gi Light 2D Feature "settings :
ScaleMode:Scale - Ratio 2
RayNum:100
--------------------------------------------
ScreenResolution:2560 * 1440 ( Both in the editor and the standalone app)
--------------------------------------------
PC configuration:
 gpu :NVDIA 4080 LaptopGPU   cpu:i9-13900HX

Also when I try to export a Development build and enable the autoconnect Profiler. I can see the Vsync is still exist although I have disable it in the editor or by scripts.

![](https://i.imgur.com/w1aREDu.png)

**Comment by NullTale** [comment]
Thanks, 'll take it into account.

**Comment by Wenzy--** [comment]
If you are busy, you can just ignore this thread. I didn't expect the author to directly solve this issue. What I am trying to do is provide enough details to help identify the bug, not just for myself but also to assist others who may encounter a similar problem. I am concerned whether this is a universal issue or if it is caused by settings on my side.

If you said you can't reproduce the bug, that's enough. I will perform more testing. This repository is still great. I am just trying to improve the framerate as much as possible.
