### ISSUE TITLE
Jump Flooding Algorithm has line artifacts

### ISSUE THREAD

**Issue by killereks** [NullTale/GiLight2D#2]
![image](https://github.com/NullTale/GiLight2D/assets/10748374/b777e188-2775-4d20-b710-5a9bd73808c2)
There are visible vertical line artefacts that mess up shadow calculations. The picture shows _DistTex drawn on the screen at 4k.

**Comment by NullTale** [comment]
* fixed with the last commit ca30b936d1238e6200a41d0527c057f9ed5d079c (9 month, two lines of code, yeah)
* guys, I thought you could handle with it, believed in you all the way, wtf!
* can't be sure in fix at 100%, but seems it solve the problem ~
