### ISSUE TITLE
Any plans to support Render Graph for Unity 6?

### ISSUE THREAD

**Issue by ptrefall** [NullTale/GiLight2D#4]
Hi, this is a very cool project! 
When I try to add it to a Unity 6 project, I get a warning that I have to run in compatibility mode.
https://docs.unity3d.com/6000.0/Documentation/Manual/urp/compatibility-mode.html

Are there any plans to support the Render Graph API? 

Specially since the documentation states that Unity no longer develops or improves the rendering path
 that doesn’t use the render graph API. Use the render graph API instead when developing new graphics features.

**Comment by NullTale** [comment]
No, I try not to code and be distance from that things. 

The project itself was made as it is. for reason not to be just a programming tool,
that's how I overcame my creative crisis at that time, and I don't want to go back to that..

Only if somebody make a commit, but I realize that's unlikely to happen ~
